app_pairpjt1/urls.py
from django.urls import path
from . import views

app_name = "pjt1"

urlpatterns = [
    path("", views.index, name="index"),
    path("review/", views.review, name="review"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("edit/<int:pk>", views.edit, name="edit"),
    path("update/<int:pk>", views.update, name="update"),
]

pairpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_pairpjt1.urls")),
]

app_pairpjt1/models.py
from django.db import models

# Create your models here.


class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

app_pairpjt1/views.py
from django.shortcuts import render, redirect
from .models import Review

# Create your views here.


def index(request):

    reviews = Review.objects.all()
    context = {
        "reviews": reviews,
    }

    return render(request, "app_pairpjt1/index.html", context)


def review(request):

    return render(request, "app_pairpjt1/review.html")


def create(request):

    title = request.GET.get("title")
    content = request.GET.get("content")
    created_at = request.GET.get("created_at")

    Review.objects.create(title=title, content=content)

    return redirect("pjt1:index")


def detail(request, pk):

    content = Review.objects.get(pk=pk)

    context = {
        "content": content,
    }

    return render(request, "app_pairpjt1/detail.html", context)


def delete(request, pk):

    delete = Review.objects.get(pk=pk)

    delete.delete()

    return redirect("pjt1:index")


def edit(request, pk):

    edit_content = Review.objects.get(pk=pk)

    context = {
        "edit_content": edit_content,
    }

    return render(request, "app_pairpjt1/edit.html", context)


def update(request, pk):

    old_content = Review.objects.get(pk=pk)

    old_content.title = request.GET.get("title")
    old_content.content = request.GET.get("content")

    old_content.save()

    return redirect("pjt1:index")

app_pairpjt1/templates/app_pairpjt1/detail.html
{% extends 'base.html' %}
{% block content %}

<body>



  <div class="p-5">
    <div class="card text-center" style="width: 30rem; height: 20rem;">
      <div class="card-body">
        <h5 class="card-title py-3">제목 : {{ content.title }}</h5>
        <p class="card-text py-3">{{ content.content }}</p>
        <div class="position-absolute bottom-0 end-0 p-3">

          <a class="btn btn-primary " href="{% url 'pjt1:edit' content.pk %}">리뷰수정</a>
          <a class="btn btn-danger " href="{% url 'pjt1:delete' content.pk %}">리뷰삭제</a>
        </div>
      </div>
    </div>
  </div>






</body>

{% endblock %}

app_pairpjt1/templates/app_pairpjt1/edit.html
{% extends 'base.html' %}
{% block content %}

<body>


  <form action="{% url 'pjt1:update' edit_content.pk %}">
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">제목</label>
      <input type="text" name='title' class="form-control" id="exampleFormControlInput1"
        value="{{ edit_content.title }}">
    </div>
    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">내용</label>
      <input type="text" name="content" class="form-control" id="exampleFormControlTextarea1"
        value="{{ edit_content.content }}"></input>
    </div>
    <div class="d-grid gap-2">
      <input type="submit" class="btn btn-primary" value="리뷰수정">
    </div>
  </form>

</body>

{% endblock %}

app_pairpjt1/templates/app_pairpjt1/index.html
{% extends 'base.html' %}
{% block content %}

</div>

<body>


  <table class="table">
    <thead class="table-dark">
      <tr>
        <th scope="col">리뷰 번호</th>
        <th scope="col">리뷰 제목</th>
        <th scope="col">작성 시간</th>
      </tr>
    </thead>

    {% for review in reviews %}

    <tbody>
      <tr>
        <th scope="row">{{ review.pk }}</th>
        <td>
          <a href="{% url 'pjt1:detail' review.pk %}">{{ review.title }}</a>
        </td>
        <td>{{ review.created_at }}</td>
      </tr>
    </tbody>
    {% endfor %}
  </table>


  <div class="text-end ">

    <a class="btn btn-primary" href="{% url 'pjt1:review' %}">리뷰 작성</a>

  </div>


  <div style="height:500px ;"></div>


  <footer class="bg-dark text-white text-center fixed-bottom">
    <h2>
      2022-09-30 Django 페어 프로젝트 01 이성훈,이동현
    </h2>

  </footer>

</body>

{% endblock %}

app_pairpjt1/templates/app_pairpjt1/review.html
{% extends 'base.html' %}
{% block content %}

<body>


  <form action="{% url 'pjt1:create' %}">
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">제목</label>
      <input type="text" name='title' class="form-control" id="exampleFormControlInput1">
    </div>
    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">내용</label>
      <input type="text" name="content" class="form-control" id="exampleFormControlTextarea1"></input>
    </div>
    <div class="d-grid gap-2">
      <input type="submit" class="btn btn-primary" value="리뷰쓰기">
    </div>
  </form>

</body>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body>
  {% block content %}

  {% endblock %}

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"></script>
</body>

</html>